# Install Node.js
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json & package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Build the project
RUN npm run build

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "start"]
